### ISSUE TITLE
Found some discrepancy on commits on views.py

### ISSUE THREAD

**Issue by sanjaypradeep** [geekpius/jQuery-Django-Tutorial#1]
Commite overridden on head version.

**Comment by geekpius** [comment]
fixed

**Comment by sanjaypradeep** [comment]
![a](https://user-images.githubusercontent.com/18122757/107538255-c6b16a80-6be9-11eb-9dda-afacf59525e6.JPG)
![b](https://user-images.githubusercontent.com/18122757/107538259-c87b2e00-6be9-11eb-820c-6897ec52f8b0.JPG)
